[project]
name = "printer-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyserial>=3.5",
    "pyserial-asyncio>=0.6",
    "mido>=1.3.0",
]
